name: Audit

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  audit:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v ./...

    - name: Lint code
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Check formatting
      run: gofmt -l .